remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Yifan Ren
logo: /photo.png
description: I am currently a 1st year Ph.D. student in the Department of Computer Science & Engineering, Texas A&M University. My advisor is Prof. Shuiwang Ji, who leads the Data Integration, Visualization, and Exploration (DIVE) Laboratory.
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-minimal
